//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLightBrigade_bhaptics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheLightBrigade_bhaptics.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;category&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;uploader&quot;:&quot;Oy8xq33fqbOwk4g7ojpt1pM5pbC2&quot;,&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;AbsorbSoul&quot;,&quot;id&quot;:&quot;y1VaKMBg8MspsVnorkV3&quot;,&quot;media&quot;:{&quot;name&quot;:&quot;&quot;,&quot;mediaType&quot;:&quot;None&quot;,&quot;description&quot;:&quot;&quot;,&quot;link&quot;:&quot;&quot;,&quot;updateTime&quot;:0,&quot;duration&quot;:0},&quot;description&quot;:&quot;&quot;,&quot;tracks&quot;:[{&quot;enable&quot;:true,&quot;effects&quot;:[{&quot;name&quot;:&quot;Effect 1&quot;,&quot;offsetTime&quot;:249,&quot;startTime&quot;:0,&quot;modes&quot;:{&quot;VestFront&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;pathMode&quot;:{&quot;feedback&quot;:[{&quot;movingPattern&quot;:&quot;CONST_SPEED&quot;,&quot;playbackType&quot;:&quot;FADE_OUT&quot;,&quot;visible&quot;:true,&quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AbsorbSoul {
            get {
                return ResourceManager.GetString("AbsorbSoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1644938948308,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string AbsorbTarotCard {
            get {
                return ResourceManager.GetString("AbsorbTarotCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;category&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;uploader&quot;:&quot;Oy8xq33fqbOwk4g7ojpt1pM5pbC2&quot;,&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;AreaClear&quot;,&quot;id&quot;:&quot;qBokCq1WGwcanL0HySut&quot;,&quot;media&quot;:{&quot;name&quot;:&quot;&quot;,&quot;mediaType&quot;:&quot;None&quot;,&quot;description&quot;:&quot;&quot;,&quot;link&quot;:&quot;&quot;,&quot;updateTime&quot;:0,&quot;duration&quot;:0},&quot;description&quot;:&quot;&quot;,&quot;tracks&quot;:[{&quot;enable&quot;:true,&quot;effects&quot;:[{&quot;name&quot;:&quot;Effect 1&quot;,&quot;offsetTime&quot;:750,&quot;startTime&quot;:0,&quot;modes&quot;:{&quot;VestFront&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;pathMode&quot;:{&quot;feedback&quot;:[{&quot;movingPattern&quot;:&quot;CONST_TDM&quot;,&quot;playbackType&quot;:&quot;FADE_OUT&quot;,&quot;visible&quot;:true,&quot;poin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AreaClear {
            get {
                return ResourceManager.GetString("AreaClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638263410870,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string BellyRumble {
            get {
                return ResourceManager.GetString("BellyRumble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638188783954,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string BladeHit {
            get {
                return ResourceManager.GetString("BladeHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638178631813,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string BulletHit {
            get {
                return ResourceManager.GetString("BulletHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1637779892190,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string ExplosionFace {
            get {
                return ResourceManager.GetString("ExplosionFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1637779829361,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string ExplosionUp {
            get {
                return ResourceManager.GetString("ExplosionUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;category&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;uploader&quot;:&quot;Oy8xq33fqbOwk4g7ojpt1pM5pbC2&quot;,&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;FootStep_L&quot;,&quot;id&quot;:&quot;0MVrtz0cT0oQGM8shxWW&quot;,&quot;media&quot;:{&quot;name&quot;:&quot;&quot;,&quot;mediaType&quot;:&quot;None&quot;,&quot;description&quot;:&quot;&quot;,&quot;link&quot;:&quot;&quot;,&quot;updateTime&quot;:0,&quot;duration&quot;:0},&quot;description&quot;:&quot;&quot;,&quot;tracks&quot;:[{&quot;enable&quot;:true,&quot;effects&quot;:[{&quot;name&quot;:&quot;Effect 1&quot;,&quot;offsetTime&quot;:249,&quot;startTime&quot;:0,&quot;modes&quot;:{&quot;FootL&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;pathMode&quot;:{&quot;feedback&quot;:[{&quot;movingPattern&quot;:&quot;CONST_SPEED&quot;,&quot;playbackType&quot;:&quot;FADE_OUT&quot;,&quot;visible&quot;:true,&quot;point [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FootStep_L {
            get {
                return ResourceManager.GetString("FootStep_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;category&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;uploader&quot;:&quot;Oy8xq33fqbOwk4g7ojpt1pM5pbC2&quot;,&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;FootStep_R&quot;,&quot;id&quot;:&quot;q7BkTOHBdk2TvAupncfV&quot;,&quot;media&quot;:{&quot;name&quot;:&quot;&quot;,&quot;mediaType&quot;:&quot;None&quot;,&quot;description&quot;:&quot;&quot;,&quot;link&quot;:&quot;&quot;,&quot;updateTime&quot;:0,&quot;duration&quot;:0},&quot;description&quot;:&quot;&quot;,&quot;tracks&quot;:[{&quot;enable&quot;:true,&quot;effects&quot;:[{&quot;name&quot;:&quot;Effect 1&quot;,&quot;offsetTime&quot;:249,&quot;startTime&quot;:0,&quot;modes&quot;:{&quot;FootL&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;pathMode&quot;:{&quot;feedback&quot;:[]},&quot;mode&quot;:&quot;PATH_MODE&quot;},&quot;FootR&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FootStep_R {
            get {
                return ResourceManager.GetString("FootStep_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1640066104495,&quot;description&quot;:&quot;&quot;,&quot;id&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;Head&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:1,&quot;x&quot;:0.2,&quot;y&quot;:0.5},{&quot;index&quot;:2,&quot;x&quot;:0.4,&quot;y&quot;:0.5},{&quot;index&quot;:3,&quot;x&quot;:0.6,&quot;y&quot;:0.5},{&quot;index&quot;:4,&quot;x&quot;:0.8,&quot;y&quot;:0.5},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:0.5}]},&quot;name&quot;:&quot;Tactal&quot;,&quot;type&quot;:&quot;Tactal&quot;},&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;Headshot_B&quot;,&quot;tracks&quot;:[{&quot;effects&quot;:[{&quot;modes&quot;:{&quot;Head&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[{&quot;endTime&quot;:164,&quot;playbackType&quot;:&quot;NONE&quot;,&quot;pointList&quot;:[{&quot;index&quot;:0,&quot;intensity&quot;:1},{&quot;index&quot;:5,&quot;intensi [rest of string was tru....
        /// </summary>
        internal static string Headshot_B {
            get {
                return ResourceManager.GetString("Headshot_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1640066060930,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;Head&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:1,&quot;x&quot;:0.2,&quot;y&quot;:0.5},{&quot;index&quot;:2,&quot;x&quot;:0.4,&quot;y&quot;:0.5},{&quot;index&quot;:3,&quot;x&quot;:0.6,&quot;y&quot;:0.5},{&quot;index&quot;:4,&quot;x&quot;:0.8,&quot;y&quot;:0.5},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:0.5}]},&quot;name&quot;:&quot;Tactal&quot;,&quot;type&quot;:&quot;Tactal&quot;},&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;Headshot_F&quot;,&quot;tracks&quot;:[{&quot;effects&quot;:[{&quot;modes&quot;:{&quot;Head&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[{&quot;endTime&quot;:164,&quot;playbackType&quot;:&quot;NONE&quot;,&quot;pointList&quot;:[{&quot;index&quot;:2,&quot;intensity&quot;:1},{&quot;index&quot;:3,&quot;intensity&quot;:1}], [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Headshot_F {
            get {
                return ResourceManager.GetString("Headshot_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1640066132291,&quot;description&quot;:&quot;&quot;,&quot;id&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;Head&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:1,&quot;x&quot;:0.2,&quot;y&quot;:0.5},{&quot;index&quot;:2,&quot;x&quot;:0.4,&quot;y&quot;:0.5},{&quot;index&quot;:3,&quot;x&quot;:0.6,&quot;y&quot;:0.5},{&quot;index&quot;:4,&quot;x&quot;:0.8,&quot;y&quot;:0.5},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:0.5}]},&quot;name&quot;:&quot;Tactal&quot;,&quot;type&quot;:&quot;Tactal&quot;},&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;Headshot_L&quot;,&quot;tracks&quot;:[{&quot;effects&quot;:[{&quot;modes&quot;:{&quot;Head&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[{&quot;endTime&quot;:164,&quot;playbackType&quot;:&quot;NONE&quot;,&quot;pointList&quot;:[{&quot;index&quot;:1,&quot;intensity&quot;:1},{&quot;index&quot;:0,&quot;intensi [rest of string was tru....
        /// </summary>
        internal static string Headshot_L {
            get {
                return ResourceManager.GetString("Headshot_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1640066155941,&quot;description&quot;:&quot;&quot;,&quot;id&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;Head&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:1,&quot;x&quot;:0.2,&quot;y&quot;:0.5},{&quot;index&quot;:2,&quot;x&quot;:0.4,&quot;y&quot;:0.5},{&quot;index&quot;:3,&quot;x&quot;:0.6,&quot;y&quot;:0.5},{&quot;index&quot;:4,&quot;x&quot;:0.8,&quot;y&quot;:0.5},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:0.5}]},&quot;name&quot;:&quot;Tactal&quot;,&quot;type&quot;:&quot;Tactal&quot;},&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;Headshot_R&quot;,&quot;tracks&quot;:[{&quot;effects&quot;:[{&quot;modes&quot;:{&quot;Head&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[{&quot;endTime&quot;:164,&quot;playbackType&quot;:&quot;NONE&quot;,&quot;pointList&quot;:[{&quot;index&quot;:4,&quot;intensity&quot;:1},{&quot;index&quot;:5,&quot;intensi [rest of string was tru....
        /// </summary>
        internal static string Headshot_R {
            get {
                return ResourceManager.GetString("Headshot_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638185577152,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string HeadShotVest {
            get {
                return ResourceManager.GetString("HeadShotVest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638977064136,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string Healing {
            get {
                return ResourceManager.GetString("Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1589039716311,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string HeartBeat {
            get {
                return ResourceManager.GetString("HeartBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638188520628,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string Impact {
            get {
                return ResourceManager.GetString("Impact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1644938948308,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string LevelUp {
            get {
                return ResourceManager.GetString("LevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1658915090745,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string Poison {
            get {
                return ResourceManager.GetString("Poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;category&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;uploader&quot;:&quot;Oy8xq33fqbOwk4g7ojpt1pM5pbC2&quot;,&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;PrayerArms&quot;,&quot;id&quot;:&quot;QYuQa3k2f1O1CNy8n74k&quot;,&quot;media&quot;:{&quot;name&quot;:&quot;&quot;,&quot;mediaType&quot;:&quot;None&quot;,&quot;description&quot;:&quot;&quot;,&quot;link&quot;:&quot;&quot;,&quot;updateTime&quot;:0,&quot;duration&quot;:0},&quot;description&quot;:&quot;&quot;,&quot;tracks&quot;:[{&quot;enable&quot;:true,&quot;effects&quot;:[{&quot;name&quot;:&quot;Effect 1&quot;,&quot;startTime&quot;:159,&quot;offsetTime&quot;:239,&quot;modes&quot;:{&quot;ForearmL&quot;:{&quot;mode&quot;:&quot;PATH_MODE&quot;,&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;pathMode&quot;:{&quot;feedback&quot;:[{&quot;playbackType&quot;:&quot;NONE&quot;,&quot;movingPattern&quot;:&quot;CONST_SPEED&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrayerArms {
            get {
                return ResourceManager.GetString("PrayerArms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;category&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;uploader&quot;:&quot;Oy8xq33fqbOwk4g7ojpt1pM5pbC2&quot;,&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;PrayerHands&quot;,&quot;id&quot;:&quot;NdzM1BcLXNeNgPUKZunE&quot;,&quot;media&quot;:{&quot;name&quot;:&quot;&quot;,&quot;mediaType&quot;:&quot;None&quot;,&quot;description&quot;:&quot;&quot;,&quot;link&quot;:&quot;&quot;,&quot;updateTime&quot;:0,&quot;duration&quot;:0},&quot;description&quot;:&quot;&quot;,&quot;tracks&quot;:[{&quot;enable&quot;:true,&quot;effects&quot;:[{&quot;name&quot;:&quot;Effect 1&quot;,&quot;offsetTime&quot;:239,&quot;startTime&quot;:0,&quot;modes&quot;:{&quot;HandR&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;pathMode&quot;:{&quot;feedback&quot;:[{&quot;movingPattern&quot;:&quot;CONST_SPEED&quot;,&quot;playbackType&quot;:&quot;NONE&quot;,&quot;visible&quot;:true,&quot;pointLis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrayerHands {
            get {
                return ResourceManager.GetString("PrayerHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;category&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;uploader&quot;:&quot;Oy8xq33fqbOwk4g7ojpt1pM5pbC2&quot;,&quot;mediaFileDuration&quot;:1.5,&quot;name&quot;:&quot;PrayerVest&quot;,&quot;id&quot;:&quot;WqgOxy8um8yx3WiAZviJ&quot;,&quot;media&quot;:{&quot;name&quot;:&quot;&quot;,&quot;mediaType&quot;:&quot;None&quot;,&quot;description&quot;:&quot;&quot;,&quot;link&quot;:&quot;&quot;,&quot;updateTime&quot;:0,&quot;duration&quot;:0},&quot;description&quot;:&quot;&quot;,&quot;tracks&quot;:[{&quot;enable&quot;:true,&quot;effects&quot;:[{&quot;name&quot;:&quot;Effect 1&quot;,&quot;startTime&quot;:299,&quot;offsetTime&quot;:755,&quot;modes&quot;:{&quot;VestFront&quot;:{&quot;mode&quot;:&quot;PATH_MODE&quot;,&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;pathMode&quot;:{&quot;feedback&quot;:[{&quot;playbackType&quot;:&quot;NONE&quot;,&quot;movingPattern&quot;:&quot;CONST_SPEED [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrayerVest {
            get {
                return ResourceManager.GetString("PrayerVest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;category&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;uploader&quot;:&quot;Oy8xq33fqbOwk4g7ojpt1pM5pbC2&quot;,&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;ReceiveAmmo_L&quot;,&quot;id&quot;:&quot;bPWOt6pLRr5QumoBqn72&quot;,&quot;media&quot;:{&quot;name&quot;:&quot;&quot;,&quot;mediaType&quot;:&quot;None&quot;,&quot;description&quot;:&quot;&quot;,&quot;link&quot;:&quot;&quot;,&quot;updateTime&quot;:0,&quot;duration&quot;:0},&quot;description&quot;:&quot;&quot;,&quot;tracks&quot;:[{&quot;enable&quot;:true,&quot;effects&quot;:[{&quot;name&quot;:&quot;Effect 1&quot;,&quot;offsetTime&quot;:204,&quot;startTime&quot;:0,&quot;modes&quot;:{&quot;VestFront&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;pathMode&quot;:{&quot;feedback&quot;:[{&quot;movingPattern&quot;:&quot;CONST_SPEED&quot;,&quot;playbackType&quot;:&quot;FADE_IN&quot;,&quot;visible&quot;:true, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReceiveAmmo_L {
            get {
                return ResourceManager.GetString("ReceiveAmmo_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;category&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;uploader&quot;:&quot;Oy8xq33fqbOwk4g7ojpt1pM5pbC2&quot;,&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;ReceiveAmmo_R&quot;,&quot;id&quot;:&quot;AmfofNIkx28rnPlbaNAW&quot;,&quot;media&quot;:{&quot;name&quot;:&quot;&quot;,&quot;mediaType&quot;:&quot;None&quot;,&quot;description&quot;:&quot;&quot;,&quot;link&quot;:&quot;&quot;,&quot;updateTime&quot;:0,&quot;duration&quot;:0},&quot;description&quot;:&quot;&quot;,&quot;tracks&quot;:[{&quot;enable&quot;:true,&quot;effects&quot;:[{&quot;name&quot;:&quot;Effect 1&quot;,&quot;offsetTime&quot;:204,&quot;startTime&quot;:0,&quot;modes&quot;:{&quot;VestFront&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;pathMode&quot;:{&quot;feedback&quot;:[{&quot;movingPattern&quot;:&quot;CONST_SPEED&quot;,&quot;playbackType&quot;:&quot;FADE_IN&quot;,&quot;visible&quot;:true, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReceiveAmmo_R {
            get {
                return ResourceManager.GetString("ReceiveAmmo_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638092429694,&quot;description&quot;:&quot;&quot;,&quot;id&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;ForearmL&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:0,&quot;y&quot;:1},{&quot;index&quot;:4,&quot;x&quot;:0.5,&quot;y&quot;:1},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:1}],&quot;ForearmR&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:0,&quot;y&quot;:1},{&quot;index&quot;:4,&quot;x&quot;:0.5,&quot;y&quot;:1},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:1}]},&quot;name&quot;:&quot;Tactosy2&quot;,&quot;type&quot;:&quot;Tactosy2&quot;},&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;Recoil_L&quot;,&quot;t....
        /// </summary>
        internal static string RecoilArms_L {
            get {
                return ResourceManager.GetString("RecoilArms_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638092279252,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;ForearmL&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:0,&quot;y&quot;:1},{&quot;index&quot;:4,&quot;x&quot;:0.5,&quot;y&quot;:1},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:1}],&quot;ForearmR&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:0,&quot;y&quot;:1},{&quot;index&quot;:4,&quot;x&quot;:0.5,&quot;y&quot;:1},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:1}]},&quot;name&quot;:&quot;Tactosy2&quot;,&quot;type&quot;:&quot;Tactosy2&quot;},&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;Recoil_R&quot;,&quot;tracks&quot;:[{&quot;effects&....
        /// </summary>
        internal static string RecoilArms_R {
            get {
                return ResourceManager.GetString("RecoilArms_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1639994399110,&quot;description&quot;:&quot;&quot;,&quot;id&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;HandL&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0.5},{&quot;index&quot;:2,&quot;x&quot;:0.5,&quot;y&quot;:1}],&quot;HandR&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0.5},{&quot;index&quot;:2,&quot;x&quot;:0.5,&quot;y&quot;:1}]},&quot;name&quot;:&quot;TactosyH&quot;,&quot;type&quot;:&quot;Hand&quot;},&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;RecoilPistolHands_L&quot;,&quot;tracks&quot;:[{&quot;effects&quot;:[{&quot;modes&quot;:{&quot;HandL&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[{&quot;endTime&quot;:148,&quot;playbackType&quot;:&quot;NONE&quot;,&quot;pointList&quot;:[{&quot;index&quot;:0,&quot;intensity&quot;:0.8}, [rest of string was truncate....
        /// </summary>
        internal static string RecoilHands_L {
            get {
                return ResourceManager.GetString("RecoilHands_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1639982868786,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;HandL&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0.5},{&quot;index&quot;:2,&quot;x&quot;:0.5,&quot;y&quot;:1}],&quot;HandR&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0.5},{&quot;index&quot;:2,&quot;x&quot;:0.5,&quot;y&quot;:1}]},&quot;name&quot;:&quot;TactosyH&quot;,&quot;type&quot;:&quot;Hand&quot;},&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;RecoilPistolHands_R&quot;,&quot;tracks&quot;:[{&quot;effects&quot;:[{&quot;modes&quot;:{&quot;HandL&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;mode&quot;:&quot;DOT_MODE&quot;,&quot;pathMode&quot;:{&quot;feedback&quot;:[]}},&quot;HandR&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:fa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecoilHands_R {
            get {
                return ResourceManager.GetString("RecoilHands_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638092655435,&quot;description&quot;:&quot;&quot;,&quot;id&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14....
        /// </summary>
        internal static string RecoilVest_L {
            get {
                return ResourceManager.GetString("RecoilVest_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638092523947,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string RecoilVest_R {
            get {
                return ResourceManager.GetString("RecoilVest_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;category&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;uploader&quot;:&quot;Oy8xq33fqbOwk4g7ojpt1pM5pbC2&quot;,&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;RifleReceive&quot;,&quot;id&quot;:&quot;nzt3IdJyJ58bsvgc8FeU&quot;,&quot;media&quot;:{&quot;name&quot;:&quot;&quot;,&quot;mediaType&quot;:&quot;None&quot;,&quot;description&quot;:&quot;&quot;,&quot;link&quot;:&quot;&quot;,&quot;updateTime&quot;:0,&quot;duration&quot;:0},&quot;description&quot;:&quot;&quot;,&quot;tracks&quot;:[{&quot;enable&quot;:true,&quot;effects&quot;:[{&quot;name&quot;:&quot;Effect 1&quot;,&quot;offsetTime&quot;:439,&quot;startTime&quot;:0,&quot;modes&quot;:{&quot;VestFront&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[{&quot;startTime&quot;:0,&quot;endTime&quot;:439,&quot;playbackType&quot;:&quot;NONE&quot;,&quot;pointList&quot;:[]}]},&quot;pathMode&quot;:{&quot;feedback&quot;:[]},&quot;mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RifleReceive {
            get {
                return ResourceManager.GetString("RifleReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;category&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;uploader&quot;:&quot;Oy8xq33fqbOwk4g7ojpt1pM5pbC2&quot;,&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;RifleStore&quot;,&quot;id&quot;:&quot;aGk2uai49F6kw3ts0Fnr&quot;,&quot;media&quot;:{&quot;name&quot;:&quot;&quot;,&quot;mediaType&quot;:&quot;None&quot;,&quot;description&quot;:&quot;&quot;,&quot;link&quot;:&quot;&quot;,&quot;updateTime&quot;:0,&quot;duration&quot;:0},&quot;description&quot;:&quot;&quot;,&quot;tracks&quot;:[{&quot;enable&quot;:true,&quot;effects&quot;:[{&quot;name&quot;:&quot;Effect 1&quot;,&quot;offsetTime&quot;:439,&quot;startTime&quot;:0,&quot;modes&quot;:{&quot;VestFront&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[{&quot;startTime&quot;:0,&quot;endTime&quot;:439,&quot;playbackType&quot;:&quot;NONE&quot;,&quot;pointList&quot;:[]}]},&quot;pathMode&quot;:{&quot;feedback&quot;:[]},&quot;mode [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RifleStore {
            get {
                return ResourceManager.GetString("RifleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1637413732351,&quot;description&quot;:&quot;&quot;,&quot;id&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14....
        /// </summary>
        internal static string ShootBowVest_L {
            get {
                return ResourceManager.GetString("ShootBowVest_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1637413537989,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string ShootBowVest_R {
            get {
                return ResourceManager.GetString("ShootBowVest_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1641200606200,&quot;description&quot;:&quot;&quot;,&quot;id&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;ForearmL&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:0,&quot;y&quot;:1},{&quot;index&quot;:4,&quot;x&quot;:0.5,&quot;y&quot;:1},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:1}],&quot;ForearmR&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:0,&quot;y&quot;:1},{&quot;index&quot;:4,&quot;x&quot;:0.5,&quot;y&quot;:1},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:1}]},&quot;name&quot;:&quot;Tactosy2&quot;,&quot;type&quot;:&quot;Tactosy2&quot;},&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;SpellShootArm_L&quot;,....
        /// </summary>
        internal static string SpellArm_L {
            get {
                return ResourceManager.GetString("SpellArm_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1641200480668,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;ForearmL&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:0,&quot;y&quot;:1},{&quot;index&quot;:4,&quot;x&quot;:0.5,&quot;y&quot;:1},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:1}],&quot;ForearmR&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:0,&quot;y&quot;:1},{&quot;index&quot;:4,&quot;x&quot;:0.5,&quot;y&quot;:1},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:1}]},&quot;name&quot;:&quot;Tactosy2&quot;,&quot;type&quot;:&quot;Tactosy2&quot;},&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;SpellShootArm_R&quot;,&quot;tracks&quot;:[{&quot;e....
        /// </summary>
        internal static string SpellArm_R {
            get {
                return ResourceManager.GetString("SpellArm_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1641200697466,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;HandL&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0.5},{&quot;index&quot;:2,&quot;x&quot;:0.5,&quot;y&quot;:1}],&quot;HandR&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0.5},{&quot;index&quot;:2,&quot;x&quot;:0.5,&quot;y&quot;:1}]},&quot;name&quot;:&quot;TactosyH&quot;,&quot;type&quot;:&quot;Hand&quot;},&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;SpellShootHand_R&quot;,&quot;tracks&quot;:[{&quot;effects&quot;:[{&quot;modes&quot;:{&quot;HandL&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;mode&quot;:&quot;PATH_MODE&quot;,&quot;pathMode&quot;:{&quot;feedback&quot;:[]}},&quot;HandR&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:fals [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpellHand_L {
            get {
                return ResourceManager.GetString("SpellHand_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1641200852041,&quot;description&quot;:&quot;&quot;,&quot;id&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;HandL&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0.5},{&quot;index&quot;:2,&quot;x&quot;:0.5,&quot;y&quot;:1}],&quot;HandR&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0.5},{&quot;index&quot;:2,&quot;x&quot;:0.5,&quot;y&quot;:1}]},&quot;name&quot;:&quot;TactosyH&quot;,&quot;type&quot;:&quot;Hand&quot;},&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;SpellShootHand_L&quot;,&quot;tracks&quot;:[{&quot;effects&quot;:[{&quot;modes&quot;:{&quot;HandL&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;mode&quot;:&quot;PATH_MODE&quot;,&quot;pathMode&quot;:{&quot;feedback&quot;:[]}},&quot;HandR&quot;:{&quot;dotMode&quot;:{&quot;dotConnect [rest of string was tru....
        /// </summary>
        internal static string SpellHand_R {
            get {
                return ResourceManager.GetString("SpellHand_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1641200375582,&quot;description&quot;:&quot;&quot;,&quot;id&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14....
        /// </summary>
        internal static string SpellVest_L {
            get {
                return ResourceManager.GetString("SpellVest_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1641199897212,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string SpellVest_R {
            get {
                return ResourceManager.GetString("SpellVest_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;category&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;uploader&quot;:&quot;Oy8xq33fqbOwk4g7ojpt1pM5pbC2&quot;,&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;StoreAmmo_L&quot;,&quot;id&quot;:&quot;e8Cwhs5rfBqwBhM5rHX7&quot;,&quot;media&quot;:{&quot;name&quot;:&quot;&quot;,&quot;mediaType&quot;:&quot;None&quot;,&quot;description&quot;:&quot;&quot;,&quot;link&quot;:&quot;&quot;,&quot;updateTime&quot;:0,&quot;duration&quot;:0},&quot;description&quot;:&quot;&quot;,&quot;tracks&quot;:[{&quot;enable&quot;:true,&quot;effects&quot;:[{&quot;name&quot;:&quot;Effect 1&quot;,&quot;offsetTime&quot;:204,&quot;startTime&quot;:0,&quot;modes&quot;:{&quot;VestFront&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;pathMode&quot;:{&quot;feedback&quot;:[{&quot;movingPattern&quot;:&quot;CONST_SPEED&quot;,&quot;playbackType&quot;:&quot;FADE_IN&quot;,&quot;visible&quot;:true,&quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreAmmo_L {
            get {
                return ResourceManager.GetString("StoreAmmo_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;category&quot;:&quot;&quot;,&quot;tags&quot;:[],&quot;uploader&quot;:&quot;Oy8xq33fqbOwk4g7ojpt1pM5pbC2&quot;,&quot;mediaFileDuration&quot;:1,&quot;name&quot;:&quot;StoreAmmo_R&quot;,&quot;id&quot;:&quot;wFVumDez2eMo2eYvwuYY&quot;,&quot;media&quot;:{&quot;name&quot;:&quot;&quot;,&quot;mediaType&quot;:&quot;None&quot;,&quot;description&quot;:&quot;&quot;,&quot;link&quot;:&quot;&quot;,&quot;updateTime&quot;:0,&quot;duration&quot;:0},&quot;description&quot;:&quot;&quot;,&quot;tracks&quot;:[{&quot;enable&quot;:true,&quot;effects&quot;:[{&quot;name&quot;:&quot;Effect 1&quot;,&quot;offsetTime&quot;:204,&quot;startTime&quot;:0,&quot;modes&quot;:{&quot;VestFront&quot;:{&quot;dotMode&quot;:{&quot;dotConnected&quot;:false,&quot;feedback&quot;:[]},&quot;pathMode&quot;:{&quot;feedback&quot;:[{&quot;movingPattern&quot;:&quot;CONST_SPEED&quot;,&quot;playbackType&quot;:&quot;FADE_IN&quot;,&quot;visible&quot;:true,&quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreAmmo_R {
            get {
                return ResourceManager.GetString("StoreAmmo_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638178804962,&quot;description&quot;:&quot;&quot;,&quot;id&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;ForearmL&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:0,&quot;y&quot;:1},{&quot;index&quot;:4,&quot;x&quot;:0.5,&quot;y&quot;:1},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:1}],&quot;ForearmR&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:0,&quot;y&quot;:1},{&quot;index&quot;:4,&quot;x&quot;:0.5,&quot;y&quot;:1},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:1}]},&quot;name&quot;:&quot;Tactosy2&quot;,&quot;type&quot;:&quot;Tactosy2&quot;},&quot;mediaFileDuration&quot;:3,&quot;name&quot;:&quot;Sword_L&quot;,&quot;tr....
        /// </summary>
        internal static string SwordArms_L {
            get {
                return ResourceManager.GetString("SwordArms_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638178726232,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;ForearmL&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:0,&quot;y&quot;:1},{&quot;index&quot;:4,&quot;x&quot;:0.5,&quot;y&quot;:1},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:1}],&quot;ForearmR&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.5,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:0,&quot;y&quot;:1},{&quot;index&quot;:4,&quot;x&quot;:0.5,&quot;y&quot;:1},{&quot;index&quot;:5,&quot;x&quot;:1,&quot;y&quot;:1}]},&quot;name&quot;:&quot;Tactosy2&quot;,&quot;type&quot;:&quot;Tactosy2&quot;},&quot;mediaFileDuration&quot;:3,&quot;name&quot;:&quot;Sword_R&quot;,&quot;tracks&quot;:[{&quot;effects&q....
        /// </summary>
        internal static string SwordArms_R {
            get {
                return ResourceManager.GetString("SwordArms_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638178980565,&quot;description&quot;:&quot;&quot;,&quot;id&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14....
        /// </summary>
        internal static string SwordVest_L {
            get {
                return ResourceManager.GetString("SwordVest_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1638178853281,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string SwordVest_R {
            get {
                return ResourceManager.GetString("SwordVest_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;project&quot;:{&quot;createdAt&quot;:1658840563636,&quot;description&quot;:&quot;&quot;,&quot;layout&quot;:{&quot;layouts&quot;:{&quot;VestBack&quot;:[{&quot;index&quot;:0,&quot;x&quot;:0,&quot;y&quot;:0},{&quot;index&quot;:1,&quot;x&quot;:0.333,&quot;y&quot;:0},{&quot;index&quot;:2,&quot;x&quot;:0.667,&quot;y&quot;:0},{&quot;index&quot;:3,&quot;x&quot;:1,&quot;y&quot;:0},{&quot;index&quot;:4,&quot;x&quot;:0,&quot;y&quot;:0.25},{&quot;index&quot;:5,&quot;x&quot;:0.333,&quot;y&quot;:0.25},{&quot;index&quot;:6,&quot;x&quot;:0.667,&quot;y&quot;:0.25},{&quot;index&quot;:7,&quot;x&quot;:1,&quot;y&quot;:0.25},{&quot;index&quot;:8,&quot;x&quot;:0,&quot;y&quot;:0.5},{&quot;index&quot;:9,&quot;x&quot;:0.333,&quot;y&quot;:0.5},{&quot;index&quot;:10,&quot;x&quot;:0.667,&quot;y&quot;:0.5},{&quot;index&quot;:11,&quot;x&quot;:1,&quot;y&quot;:0.5},{&quot;index&quot;:12,&quot;x&quot;:0,&quot;y&quot;:0.75},{&quot;index&quot;:13,&quot;x&quot;:0.333,&quot;y&quot;:0.75},{&quot;index&quot;:14,&quot;x&quot;:0.667,&quot;y....
        /// </summary>
        internal static string Teleport {
            get {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }
    }
}
